# Site settings
title: Grupo de Usuarios PHP de Santa Catarina
email: contato@phpsc.com.br
description: > # this means to ignore newlines until "baseurl:"
  PHPSC
  Grupo de Usuarios PHP de Santa catarina.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.phpsc.com.br" # the base hostname & protocol for your site

# Social
twitter_username: PHP_SC
github_username: PHPSC

# Build settings
markdown: redcarpet
highlighter: pygments
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 3
pagination_path: "/:num"

# Plugins
gems:
  - jekyll-sitemap

sass:
  style: compressed